### ISSUE TITLE
Does not restore instance state

### ISSUE THREAD

**Issue by LouisCAD** [Steppschuh/Sensor-Data-Logger#1]
Hi!
First, thanks for your nice looking and useful app!
I tried to check the "Device orientation" sensor and rotate my phone, but all the history is discarded when the Activity is recreated.
I would advise that you handle state saving/restoration, and add configChanges with orientation in the manifest to prevent activity recreation for performance purposes (especially if used with multiwindow)

**Comment by Steppschuh** [comment]
Hey,
thanks for your input, will definitely implement your suggestions!

**Comment by Steppschuh** [comment]
Please check out the latest update, you can get the beta version here: [Google Play](https://play.google.com/apps/testing/net.steppschuh.sensordatalogger)

**Comment by LouisCAD** [comment]
Just installed the beta and tested: It works flawlessly! Double thanks for
the fix and the quickness!!
