### ISSUE TITLE
Licensing Sensor Data Logger

### ISSUE THREAD

**Issue by kimsey0** [Steppschuh/Sensor-Data-Logger#3]
Could this project [be licensed](https://help.github.com/articles/licensing-a-repository/) under an open source license, for example the MIT License?

We are a university student group that would like to use parts of the code for data collection for an activity recognition project.

**Comment by Steppschuh** [comment]
Done, feel free to use the code. Good luck with your project!

**Comment by kimsey0** [comment]
Thanks!
