### ISSUE TITLE
Sensors on Wear device Idle

### ISSUE THREAD

**Issue by aitxaz** [Steppschuh/Sensor-Data-Logger#5]
Hello, I have been trying to use the app. It's working fine on the mobile. But on the wear device it says 26 sensors Idle. No wear sensors are shown on the mobile. Mobile and wear device are paired using Wear OS and remain connected. 

Wear device is Huawei Watch 2 Sport. 

Please let me know if I'm doing something wrong. Thank you.

**Comment by Steppschuh** [comment]
Hey,
the `X sensors Idle` is the default screen you see when the app on your mobile did not request data from any of your watch's sensors. You can request sensor data from your watch by pressing the floating action button in the app on your phone.

If that's not the case, try the following in order:

- Restart your phone and watch
- Make sure that the watch is connected
- Start the app on your phone
- Start the app on your watch
- Select the sensors on your phone

**Comment by aitxaz** [comment]
It's working fine now. I had to update the SDK. Thanks a lot.

**Comment by geekfeiw** [comment]
> It's working fine now. I had to update the SDK. Thanks a lot.

Hi @aitxaz 
Did you successfully use this app to log data with Huawei Watch 2 Sport?
