### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by 532910** [Steppschuh/Sensor-Data-Logger#7]
I've opened F-Droid inclusion issue:  https://gitlab.com/fdroid/rfp/issues/842

Please help to make it available.

Could you clarify the fact that "you are not against and support the inclusion".

**Comment by Steppschuh** [comment]
I'm not against and support the inclusion.

**Comment by IzzySoft** [comment]
@Steppschuh F-Droid maintainer here. Is there a chance for a build flavor without [GMS](https://github.com/Steppschuh/Sensor-Data-Logger/blob/master/Android%20Source/datalogger/build.gradle#L46)? We cannot include an app that comes with proprietary components.

**Comment by Steppschuh** [comment]
> @Steppschuh F-Droid maintainer here. Is there a chance for a build flavor without [GMS](https://github.com/Steppschuh/Sensor-Data-Logger/blob/master/Android%20Source/datalogger/build.gradle#L46)? We cannot include an app that comes with proprietary components.

@IzzySoft No chance. Mandatory for the communication between watch and phone.

**Comment by 532910** [comment]
The watch is not mandatory for this app. The app can be used without watch.

**Comment by IzzySoft** [comment]
If you could at least have a version (APK) that comes without…

* Google Ads (Advertisement)
* Doubleclick (Advertisement)
* Google Analytics (Mobile Analytics)
* Google Tag Manager (Mobile Analytics)
* Firebase Analytics (Mobile Analytics)

I could take the app into [my repo](https://apt.izzysoft.de/fdroid/repo) (which is for F-Droid what "nonfree" is for Debian). That stuff shouldn't be mandatory, right? :innocent:

**Comment by IzzySoft** [comment]
@Steppschuh in the issue @c-e-p-x-u-o linked, the F-Droid bot reported it found Google Play Services declared in the gradle. That is a show-stopper at F-Droid. Could you provide a FOSS build-flavor?
